### ISSUE TITLE
SEARCH_SCPOPE_BASE_OBJECT error on initial import

### ISSUE THREAD

**Issue by tskirvin** [kavdev/ldap-groups#8]
On a freshly-installed CentOS 8 system where I just run 'pip3 install ldap-groups', I see:

    >>> import ldap_groups
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/site-packages/ldap_groups/__init__.py", line 1, in <module>
        from .groups import ADGroup  # noqa: F401
      File "/usr/local/lib/python3.6/site-packages/ldap_groups/groups.py", line 12, in <module>
        from ldap3 import (Server, Connection, SEARCH_SCOPE_BASE_OBJECT, SEARCH_SCOPE_WHOLE_SUBTREE, MODIFY_DELETE,
    ImportError: cannot import name 'SEARCH_SCOPE_BASE_OBJECT'

This has actually been a problem on previous releases too (e.g. RHEL7), but I was hoping that a recent install would work.

**Comment by kavdev** [comment]
@tskirvin hi there! Can you try the version on the master branch and let me know if the issue persists?

**Comment by tskirvin** [comment]
At the very least I don't see any errors, so this is progress!  I'll have to spend some time making sure everything still works.  Will you be uploading to pip?

**Comment by kavdev** [comment]
Awesome! Yep; I'm not sure why I didn't do a release last time. I'll push this out next week*
